name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: education/autograding-io-grader@v1
      with:
        test-name: Test 1
        command: "./Lab15"
        input: "7\r\n9\r\n3\r\ny\r\n14\r\n12\r\nred\r\n5\r\nn"
        expected-output: ''
        comparison-method: contains
        timeout: 10
        max-score: 15
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
      with:
        runners: test-1
